Vira/Models/YakitTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vira.Models
{
    public class YakitTakip
    {
        [Key]
        public int YakitTakipId { get; set; }
        public DateTime YakitAlimTarihi { get; set; }
        public decimal YakitAlimMiktari { get; set; }
        public decimal BaslangicKm { get; set; }
        public decimal BitisKm { get; set; }
        public decimal GidilenKm { get; set; }
        public decimal OrtalamaTuketim { get; set; }
        public int? OncekiKayitId { get; set; }

        public int AraclarId { get; set; }
        public virtual Araclar Araclar { get; set; }

    }
}

Vira/Controllers/YakitTakipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vira.Models;

namespace Vira.Controllers
{
    public class YakitTakipController : Controller
    {
        // GET: YakitTakip
        Context c = new Context();
        public ActionResult Index()
        {
            var liste = c.YakitTakips.OrderByDescending(x=> new { x.YakitAlimTarihi.Year, x.YakitAlimTarihi.Month, x.YakitAlimTarihi.Day }).ToList();
            return View(liste);
        }
        [HttpPost]
        public ActionResult ModalAc()
        {
            List<SelectListItem> aracListe = (from al in c.Araclars.ToList()
                                            select new SelectListItem
                                            {
                                                Text = al.AracPlakasi,
                                                Value = al.AraclarId.ToString()
                                            }).ToList();

            ViewBag.aListe = aracListe;

            return PartialView("YakitTakipEkle");
        }
        [HttpGet]
        public ActionResult YakitTakipEkle()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult YakitTakipEkle(YakitTakip p)
        {
            var sonYakitId = c.YakitTakips
                .Where(x => x.AraclarId == p.AraclarId)
                .OrderByDescending(y => y.YakitTakipId)
                .Select(z => z.YakitTakipId)
                .FirstOrDefault();

            if (sonYakitId != 0)
            {                
                var bKm = c.YakitTakips.Where(x => x.YakitTakipId == sonYakitId).Select(y => y.BaslangicKm).FirstOrDefault();
                var yt = c.YakitTakips.Find(sonYakitId);
                var gidilenKm = p.BaslangicKm - bKm;
                var ortTuketim = yt.YakitAlimMiktari / gidilenKm;
                yt.BitisKm = p.BaslangicKm;
                yt.GidilenKm = gidilenKm;
                yt.OrtalamaTuketim = ortTuketim;
                c.SaveChanges();
            }
            p.OncekiKayitId = sonYakitId;
            c.YakitTakips.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YakitTakipGetir(int id)
        {
            List<SelectListItem> aracListe = (from al in c.Araclars.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = al.AracPlakasi,
                                                  Value = al.AraclarId.ToString()
                                              }).ToList();

            ViewBag.aListe = aracListe;
            var yakitTakip = c.YakitTakips.Find(id);

            return PartialView("YakitTakipGetir", yakitTakip);
        }
        public ActionResult YakitTakipGuncelle(YakitTakip p)
        {
            var yakitTakip = c.YakitTakips.Find(p.YakitTakipId);
            var oncekiKayitId = c.YakitTakips.Where(x => x.YakitTakipId == p.YakitTakipId).Select(y => y.OncekiKayitId).FirstOrDefault();
            
            if (oncekiKayitId != 0)
            {
                var bKm = c.YakitTakips.Where(x => x.YakitTakipId == oncekiKayitId).Select(y => y.BaslangicKm).FirstOrDefault();
                var yt = c.YakitTakips.Find(oncekiKayitId);
                var gidilenKm = p.BaslangicKm - bKm;
                var ortTuketim = yt.YakitAlimMiktari / gidilenKm;
                yt.BitisKm = p.BaslangicKm;
                yt.GidilenKm = gidilenKm;
                yt.OrtalamaTuketim = ortTuketim;
                c.SaveChanges();
            }

            yakitTakip.AraclarId = p.AraclarId;
            yakitTakip.YakitAlimTarihi = p.YakitAlimTarihi;
            yakitTakip.YakitAlimMiktari = p.YakitAlimMiktari;
            yakitTakip.BaslangicKm = p.BaslangicKm;
            TempData["sozlesmeGuncelle"] = "";
            c.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Vira/Views/YakitTakip/Index.cshtml
@using Vira.Models
@model List<YakitTakip>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/datetime-moment.js"></script>

<div class="card card-default">
    <div class="card-header">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11">
                <strong>Yakıt Takip İşlemleri</strong>
            </h5>
            <a href="#" class="btn btn-primary ekle col-md-1" data-target="@Url.Action("ModalAc", "YakitTakip")">Yeni Kayıt</a>
        </div>
    </div>

    <!--Proje Listesi-->
    <div style="margin-left:1%; margin-right:1%">
        <br />
        <table id="liste" class="table table-bordered table-hover table-sm display" style="margin-top:20px;">
            <thead>
                <tr>
                    <th style="width:3%"><small><strong>#</strong></small></th>
                    <th style="width:10%"><small><strong>Araç/Makine Plaka</strong></small></th>
                    <th style="width:10%"><small><strong>Yakıt Alım Tarihi</strong></small></th>
                    <th style="width:10%"><small><strong>Alım Miktarı(lt)</strong></small></th>
                    <th style="width:10%"><small><strong>Başlangıç Km</strong></small></th>
                    <th style="width:10%"><small><strong>Bitiş Km</strong></small></th>
                    <th style="width:10%"><small><strong>Gidilen Km</strong></small></th>
                    <th style="width:10%"><small><strong>Ortalama Tüketim(km/lt)</strong></small></th>
                    <th style="width:5%"></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="align-middle" style="font-size:12px;"></td>
                    <td><small>@item.Araclar.AracPlakasi</small></td>
                    <td><small>@item.YakitAlimTarihi.ToString("dd.MM.yyyy")</small></td>
                    <td style="text-align:right"><small>@item.YakitAlimMiktari</small></td>
                    <td style="text-align:right"><small>@item.BaslangicKm</small></td>
                    <td style="text-align:right"><small>@item.BitisKm</small></td>
                    <td style="text-align:right"><small>@item.GidilenKm</small></td>
                    <td style="text-align:right"><small>@item.OrtalamaTuketim</small></td>
                    <td><a href="#" class="btn btn-sm btn-success guncelle" data-target="@Url.Action("YakitTakipGetir", "YakitTakip")/@item.YakitTakipId">Güncelle</a></td>
                </tr>
            }
        </table>
    </div>

    <div class="container">
        <!--Proje Ekle Modal -->
        <div class="modal fade" id="myModalE" role="dialog">
            <div class="modal-dialog modal modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--Proje Güncelle Modal -->
        <div class="modal fade" id="myModalG" role="dialog">
            <div class="modal-dialog modal modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(function () {
            $("body").on("click", ".ekle", function () {
                var url = $(this).data("target");
                $.post(url, function (data) { })
                    .done(function (data) {
                        $("#myModalE .modal-body").html(data);
                        $("#myModalE").modal("show");
                    })
                    .fail(function () {
                        $("#myModalE .modal-body").text("Hata!!");
                        $("#myModalE").modal("show");
                    })
            });
        });
        $(function () {
            $("body").on("click", ".guncelle", function () {
                var url = $(this).data("target");
                $.post(url, function (data) { })
                    .done(function (data) {
                        $("#myModalG .modal-body").html(data);
                        $("#myModalG").modal("show");
                    })
                    .fail(function () {
                        $("#myModalG .modal-body").text("Hata!!");
                        $("#myModalG").modal("show");
                    })
            });
        });

        $(document).ready(function () {
            $.fn.dataTable.moment('DD.MM.YYYY');

            var t = $('#liste').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
                },
                "columnDefs": [{
                    "searchable": false,
                    "orderable": false,
                    "targets": 0,
                }],
                "order": [[2, 'desc']]
            });
            t.on('draw.dt', function () {
                var PageInfo = $('#liste').DataTable().page.info();
                t.column(0, { page: 'current' }).nodes().each(function (cell, i) {
                    cell.innerHTML = i + 1 + PageInfo.start;
                });
            });
        });
    </script>

Vira/Views/YakitTakip/YakitTakipEkle.cshtml
@model Vira.Models.YakitTakip

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Araç/Makine Girişi</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("YakitTakipEkle", "YakitTakip")" method="post">
            <hr />
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Araç/Makine Plaka</b></label>
                    <div class="col-sm-7">
                        @Html.DropDownListFor(x => x.AraclarId, (List<SelectListItem>)ViewBag.aListe, "--- Seçiniz ---", new { @class = "form-control", @style = "width:150px", @required = "" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Yakıt Alım Tarihi</b></label>
                    <div class="col-sm-7">
                        <input style="width:160px;" type="date" class="form-control" name="YakitAlimTarihi" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Alım Miktarı(lt)</b></label>
                    <div class="col-md-7">
                        <input type="text" name="YakitAlimMiktari" class="form-control" style="width:100px; text-align:right" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Başlangıç Km</b></label>
                    <div class="col-md-7">
                        <input type="text" name="BaslangicKm" class="form-control" style="width:100px; text-align:right" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')" />
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-info">Ekle</button>
                </div>
            </div>
        </form>
    </div>
</div>

Vira/Views/YakitTakip/YakitTakipGetir.cshtml
@model Vira.Models.YakitTakip

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Sözleşme Güncelleme</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        @using (Html.BeginForm("YakitTakipGuncelle", "YakitTakip", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <hr />
            @Html.HiddenFor(x => x.YakitTakipId)
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Araç/Makine Plaka</b></label>
                    <div class="col-7">
                        @Html.DropDownListFor(x => x.AraclarId, (List<SelectListItem>)ViewBag.aListe, new { @class = "form-control", @style = "width:150px" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Yakıt Alım Tarihi</b></label>
                    <div class="col-7">
                        @Html.TextBoxFor(x => x.YakitAlimTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @style = "width:160px;", @type = "date" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Alım Miktarı(lt)</b></label>
                    <div class="col-7">
                        @Html.TextBoxFor(x => x.YakitAlimMiktari, new { @class = "form-control", @style = "width:100px; text-align:right;" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-5 text-right" style="color:red"><b>Başlangıç Km</b></label>
                    <div class="col-7">
                        @Html.TextBoxFor(x => x.BaslangicKm, new { @class = "form-control", @style = "width:100px; text-align:right;" })
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-success">Güncelle</button>
                </div>
            </div>
        }
    </div>
</div>